[package]
name = "netabase_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.111", features = ["visit", "visit-mut", "full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
